# Generated by Django 3.0.6 on 2020-05-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_auto_20200518_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.DurationField(verbose_name='Running time'),
        ),
    ]
