# Generated by Django 3.0.6 on 2020-05-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_auto_20200518_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='USD', null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='USD', null=True, verbose_name='Fees in USA'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='USD', null=True, verbose_name='Fees in world'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tagline'),
        ),
    ]
