# Generated by Django 3.0.6 on 2020-05-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0004_auto_20200518_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
