# Generated by Django 3.0.6 on 2020-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_auto_20200519_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Movie shot', 'verbose_name_plural': 'Movie shots'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.CharField(default=' – ', help_text='$', max_length=25, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.CharField(default=' – ', help_text='$', max_length=25, verbose_name='Fees in USA'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.CharField(default=' – ', help_text='$', max_length=25, verbose_name='Fees in world'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default=' – ', max_length=100, verbose_name='Tagline'),
        ),
    ]
